### ISSUE TITLE
.gitignore is not ignoring issue

### ISSUE THREAD

**Issue by Sensinki** [Sensinki/Blok-Tech-Team-4A#10]
als ik probeer .env file hidden te krijgen, dat lukt niet gewoon en heel raar dat .gitignore niet werkt. kunnen jullie hiermee kijken?

**Comment by D0nnaz** [comment]
Ja super raar, heb er naar gekeken. Heb met `git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch .env" HEAD` alle .env bestanden uit de history gekregen. Ik gok dat dit gebeurt is doordat de .env en node_modules eerder zijn aangemaakt dan de .gitignore. Ik moet ook de node_modules verwijderen en weer adden en toen werkte het pas.

@rosa33783 hou er rekening mee dat de .gitignore nog leeg is!
