### ISSUE TITLE
Database haalt de data niet die ik gestuurd heb

### ISSUE THREAD

**Issue by Sensinki** [Sensinki/Blok-Tech-Team-4A#12]
Kunnen jullie een beetje kijken naar wat ik net gepushed heb? Ik kan de data niet zien in de database en ik ben zeker dat ik het al gestuurd heb door console.log. Ik wacht jullie antwoorden?

**Comment by D0nnaz** [comment]
De code lijkt te kloppen, staat de goede uri in de db?

**Comment by Sensinki** [comment]
OMGGG! Hier staat jouw db uri. Ik was al uren lang hiermee bezig. Thankkss 🥲

**Comment by D0nnaz** [comment]
![200w](https://github.com/Sensinki/Blok-Tech-Team-4A/assets/92280247/b49cb725-51db-4679-bae0-05f3c90d4cf3)

**Comment by Sensinki** [comment]
![Wow-gif](https://github.com/Sensinki/Blok-Tech-Team-4A/assets/107122047/70de1ab6-23b1-432c-a84a-2967d0e4c18d)

**Comment by D0nnaz** [comment]
![giphy (1)](https://github.com/Sensinki/Blok-Tech-Team-4A/assets/92280247/0d36a280-4d77-4e8f-9787-4c49b26e26cf)
