### ISSUE TITLE
General to do

### ISSUE THREAD

**Issue by D0nnaz** [Sensinki/Blok-Tech-Team-4A#16]
- MVC
- CSS
- Partials handlebars
- Images compressen?

Lmk wat nog meer

**Comment by D0nnaz** [comment]
Pull requests

**Comment by Sensinki** [comment]
- Zorgen dat er maar 1x geredirect wordt naar de /match
- Juiste chats in beeld laten komen

**Comment by D0nnaz** [comment]
Presentatie voorbereiden???
Feedback vragen?

**Comment by D0nnaz** [comment]
WIKI

**Comment by D0nnaz** [comment]
Kan iemand die gzip fixen?

**Comment by D0nnaz** [comment]
Staat nu uitgebreider in discussions
