### ISSUE TITLE
Server.js not running in browser

### ISSUE THREAD

**Issue by Sensinki** [Sensinki/Blok-Tech-Team-4A#2]
I want to run de server.js but it gives me some errors. I will add here some screenshots to understand the problem better.

<img width="949" alt="Screenshot 2023-06-13 at 13 03 30" src="https://github.com/Sensinki/Blok-Tech-Team-4A/assets/107122047/8dc9336e-ca66-489b-a2a5-27e3543b1f36">

<img width="948" alt="Screenshot 2023-06-13 at 13 06 00" src="https://github.com/Sensinki/Blok-Tech-Team-4A/assets/107122047/1eba1b87-92bb-4b23-b2c2-d3d12fc0b22f">

**Comment by D0nnaz** [comment]
Dat is weer die MongoDB error die je eerder ook had, ik kan mijn code in een zipje opsturen en kijken of dat het oplost. Dit heeft met die URI te maken.

**Comment by D0nnaz** [comment]
Lag aan het feit dat ik server.js code had geschreven die anders was opgebouwd dan die van Sena, dus daardoor werkte haar code niet meer. Heb inderdaad een zipje opgestuurd en dat werkte.
