### ISSUE TITLE
Dislike button werk niet - Match

### ISSUE THREAD

**Issue by dinhs-frontend** [Sensinki/Blok-Tech-Team-4A#5]
/* eslint-disable require-jsdoc */
const profiles = [
    { name: 'Karen', image: '/Blok-Tech-Team-4A/static/css/img/profiles/Sang.cv.jpg' },
    { name: 'Abdel', image: '/Blok-Tech-Team-4A/static/css/img/profiles/abdel.jpeg' },
    { name: 'angelo', image: '/Blok-Tech-Team-4A/static/css/img/profiles/angelo.jpeg' },
    // Voeg hier meer profielen toe
  ];
  
  let currentProfileIndex = 0;
  
  document.addEventListener('DOMContentLoaded', () => {
    const dislikeButton = document.querySelector('.DisLikeButton');
    
    dislikeButton.addEventListener('click', loadNextProfile);
    
    function loadNextProfile() {
      currentProfileIndex++;
      if (currentProfileIndex >= profiles.length) {
        currentProfileIndex = 0;
      }
    
      const currentProfile = profiles[currentProfileIndex];
    
      const profileImage = document.querySelector('.userimg');
      profileImage.style.backgroundImage = `url(${currentProfile.image})`;
    
      const profileName = document.querySelector('h3');
      profileName.textContent = currentProfile.name;
    }
  });
  
  
 

<body>
    <h2>Match</h2>
    <section>
        <form id="userLike" method="POST" action="/like">
            <h3>Karen</h3>
            {{!-- <img src="img/Sang.cv.jpg" alt="Karen"> --}}
            <div class="userimg"></div>
            <p></p>
            <button type="button" class="DisLikeButton">
                <div class="heartbrokeBtn"></div>
            </button>
            <button type="submit" class="LikeButton" name="like" value="Karen">
                <div class="heartBtn"></div>
            </button>
        </form>
    </section>
    
</body>
<script src="script.js"></script>
</html>

**Comment by D0nnaz** [comment]
<body>
    <h2>Match</h2>
    <section>
        <form id="userLike" method="POST" action="/like">
            <h3>Karen</h3>
            {{!-- <img src="img/Sang.cv.jpg" alt="Karen"> --}}
            <div class="userimg"></div>
            <p></p>
            <input type="button" class="DisLikeButton">
                <div class="heartbrokeBtn"></div>
            </input>
            <input type="submit" class="LikeButton" name="like" value="Karen">
                <div class="heartBtn"></div>
            </input>
        </form>
    </section>
    
</body>

**Comment by D0nnaz** [comment]
> <body>
>     <h2>Match</h2>
>     <section>
>         <form id="userLike" method="POST" action="/like">
>             <h3>Karen</h3>
>             {{!-- <img src="img/Sang.cv.jpg" alt="Karen"> --}}
>             <div class="userimg"></div>
>             <p></p>
>             <input type="button" class="DisLikeButton">
>                 <div class="heartbrokeBtn"></div>
>             </input>
>             <input type="submit" class="LikeButton" name="like" value="Karen">
>                 <div class="heartBtn"></div>
>             </input>
>         </form>
>     </section>
>     
> </body>

**Comment by D0nnaz** [comment]
<body>
    <h2>Match</h2>
    <section>
        <form id="userLike" method="POST" action="/like">
            <h3>Karen</h3>
            {{!-- <img src="img/Sang.cv.jpg" alt="Karen"> --}}
            <div class="userimg"></div>
            <p></p>
            <input type="button" class="DisLikeButton">
                <div class="heartbrokeBtn"></div>
            </input>
            <input type="submit" class="LikeButton" name="like" value="Karen">
                <div class="heartBtn"></div>
            </input>
        </form>
    </section>
    

- </body>

**Comment by D0nnaz** [comment]
```
<body>
    <h2>Match</h2>
    <section>
        <form id="userLike" method="POST" action="/like">
            <h3>Karen</h3>
            {{!-- <img src="img/Sang.cv.jpg" alt="Karen"> --}}
            <div class="userimg"></div>
            <p></p>
            <input type="button" class="DisLikeButton">
                <div class="heartbrokeBtn"></div>
            </input>
            <input type="submit" class="LikeButton" name="like" value="Karen">
                <div class="heartBtn"></div>
            </input>
        </form>
    </section>
    
</body>
```

**Comment by D0nnaz** [comment]
Volgens mijn kan je geen submit gebruiken zonder <input>

**Comment by D0nnaz** [comment]
/* eslint-disable require-jsdoc */
const profiles = [
    { name: 'Karen', image: '/Blok-Tech-Team-4A/static/css/img/profiles/Sang.cv.jpg' },
    { name: 'Abdel', image: '/Blok-Tech-Team-4A/static/css/img/profiles/abdel.jpeg' },
    { name: 'angelo', image: '/Blok-Tech-Team-4A/static/css/img/profiles/angelo.jpeg' },
    // Voeg hier meer profielen toe
  ];
  
  let currentProfileIndex = 0;
  
  document.addEventListener('DOMContentLoaded', () => {
    const dislikeButton = document.querySelector('.DisLikeButton');
    
    dislikeButton.addEventListener('click', loadNextProfile);
    
    function loadNextProfile() {
      console.log('Clicked on DisLikeButton');
      
      currentProfileIndex++;
      if (currentProfileIndex >= profiles.length) {
        currentProfileIndex = 0;
      }
      
      console.log('Current profile index:', currentProfileIndex);
    
      const currentProfile = profiles[currentProfileIndex];
      
      console.log('Current profile:', currentProfile);
    
      const profileImage = document.querySelector('.userimg');
      profileImage.style.backgroundImage = `url(${currentProfile.image})`;
      
      console.log('Set background image:', currentProfile.image);
    
      const profileName = document.querySelector('h3');
      profileName.textContent = currentProfile.name;
      
      console.log('Set profile name:', currentProfile.name);
    }
  });
